using Data.IoC;
using Data.NHibernate;
using Entities.Entity;
using Ninject;
using NUnit.Framework;

namespace Data.Test
{
	[TestFixture]
	class AutoCreateDbTest
	{
		private StandardKernel _kernel;
		private IBaseDao _dao;
		private BaseDao BaseDao { get { return (BaseDao)_dao; } }

		[SetUp]
		public void SetUp()
		{
			_kernel = new StandardKernel(new DataModule());
			_dao = _kernel.Get<IBaseDao>();
			Assert.IsNotNull(_dao);
		}

		[Test]
		public void DoTest()
		{
			BaseDao.AutoGenerateDb();
			Assert.Pass();
		}

		[TearDown]
		public void Dispose()
		{
			_kernel.Dispose();
		}
	}
}
