using Data.NHibernate;
using NUnit.Framework;

namespace Data.Test
{
	[TestFixture]
	class AutoCreateDbTest
	{
		[Test]
		public void DoTest()
		{
			var baseDao = new BaseDao();
			baseDao.AutoGenerateDB();
			Assert.Pass();
		}
	}
}
