using System;
using System.Collections.Generic;
using System.IO;
using Common.Data.Core;
using Data.IoC;
using Data.NHibernate;
using Data.Test.Генерация_БД;
using Ninject;
using NUnit.Framework;

namespace Data.Test
{
    [TestFixture]
    class AutoCreateDbTest
    {
        private string _pathToSolution;
        public string PathToSolution
        {
            get
            {
                if (string.IsNullOrEmpty(_pathToSolution))
                {
                    var directoryName = Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().GetName().CodeBase);
                    if (directoryName != null)
                    {
                        _pathToSolution = directoryName.Remove(0, 6);
                        _pathToSolution = _pathToSolution.Remove(_pathToSolution.IndexOf("Sources", StringComparison.CurrentCultureIgnoreCase));
                    }
                }
                return _pathToSolution;
            }

        }

        private StandardKernel _kernel;
        private IBaseDao _dao;
        private BaseDao BaseDao { get { return (BaseDao)_dao; } }

        [SetUp]
        public void SetUp()
        {
            _kernel = new StandardKernel(new DataModule());
            _dao = _kernel.Get<IBaseDao>();
            Assert.IsNotNull(_dao);
        }

        [Test]
        [Ignore]
        public void GenerateTables()
        {
            BaseDao.AutoGenerateDb();
            Assert.Pass();
        }

        [Test]
        [Ignore]
        public void InsertMyData()
        {
            var setter = new MyDateSetter(PathToSolution, _dao);
            setter.Execute();
            Assert.Pass();
        }

        [Test]
        [Ignore]
        public void ConvertExchangeArchive()
        {
            var currencyTypeGenerator = new CurrencyTypeGenerator(PathToSolution);
            List<string> names = currencyTypeGenerator.GetCurrencyTypesLines();
            currencyTypeGenerator.Execute(names);

            var exchangeArchiveGenerator = new ExchangeArchiveGenerator(names, CurrencyTypeGenerator.Byr, PathToSolution);
            exchangeArchiveGenerator.Execute();

            Assert.Pass();
        }


        [TearDown]
        public void Dispose()
        {
            _kernel.Dispose();
        }
    }
}
